import { formatDate } from '../../../utils/formatters.js';

export const ParsingSummary = ({ metadata }) => {
  if (!metadata) return null;

  const stats = [
    { label: 'Status', value: metadata.parsingStatus, capitalize: true },
    { label: 'Sections Detected', value: metadata.sectionCount },
    { label: 'Characters Extracted', value: metadata.extractedCharacterCount },
    { label: 'Parser Version', value: metadata.parserVersion },
    { label: 'Processed At', value: metadata.extractionTimestamp ? formatDate(metadata.extractionTimestamp) : 'N/A' },
  ];

  return (
    <div className="bg-surface-light dark:bg-surface-dark border border-slate-200 dark:border-slate-800 rounded-lg shadow-sm overflow-hidden">
      <div className="px-4 py-5 sm:px-6 border-b border-slate-200 dark:border-slate-700">
        <h3 className="text-base font-semibold leading-6 text-slate-900 dark:text-white">Parsing Summary</h3>
        <p className="mt-1 max-w-2xl text-sm text-slate-500 dark:text-slate-400">Metadata generated by the rule-based extraction engine.</p>
      </div>
      <div className="border-t border-slate-200 dark:border-slate-700">
        <dl className="grid grid-cols-1 sm:grid-cols-2">
          {stats.map((stat, idx) => (
            <div key={stat.label} className={`px-4 py-4 sm:px-6 ${idx % 2 === 0 ? 'bg-slate-50 dark:bg-slate-800/30' : 'bg-white dark:bg-slate-900/30'}`}>
              <dt className="text-sm font-medium text-slate-500 dark:text-slate-400">{stat.label}</dt>
              <dd className={`mt-1 text-sm text-slate-900 dark:text-white sm:mt-2 ${stat.capitalize ? 'capitalize' : ''}`}>
                {stat.value || 'N/A'}
              </dd>
            </div>
          ))}
        </dl>
      </div>
    </div>
  );
};
